[release] add init 0/6 UFS910/912/922 E2 and Neutrino

diff --git a/tdt/cvs/cdk/root/release/rcS_neutrino_octagon1008 b/tdt/cvs/cdk/root/release/rcS_neutrino_octagon1008
--- a/tdt/cvs/cdk/root/release/rcS_neutrino_octagon1008
+++ b/tdt/cvs/cdk/root/release/rcS_neutrino_octagon1008
@@ -114,24 +114,30 @@ until false
 do
  echo "starting neutrino ->"
  /usr/local/bin/neutrino
- rtv=$?
- echo "neutrino ended <- RTV: " $rtv
- case "$rtv" in
-     0) echo "0"
-        echo "Box is going to sleep"
-        umount -a
-	gotosleep hdbox;;
-     1) echo "1"
-	echo "SHUTDOWN"
-        case "$var" in
-          0) fp_control -e
-    	     umount -a;;
-    	1|3) fp_control -e 
-             echo "0" > /proc/progress
-        esac;;           
-     *) echo "*"
-        echo "Unexpected error"
-        reboot;;
- esac
- done
+     rtv=$?
+      echo "neutrino ended <- RTV: " $rtv
+      case "$rtv" in
+		0) echo "0"
+		   echo "ERROR"
+      	   init 6;;
+		1) echo "1"
+		   echo "SHUTDOWN"
+		   init 0;;
+		2) echo "2"
+		   echo "REBOOT"
+		   init 6;;
+		3) echo "3"
+		   echo "RESTART"
+		   echo "0" > /proc/progress
+		   showiframe -p /boot/bootlogo.mvi &;;
+		*) echo "*"
+		   echo "ERROR"
+           init 6;;
+      esac
+   done 
 fi
+
+#never reached
+echo "REBOOT Octagon 1008" > /dev/vfd
+echo "REBOOT Octagon 1008"
+init 6
