rcS case check if 14w or 1w, gotosleep or fp_control will be used

diff --git a/tdt/cvs/cdk/root/release/rcS_neutrino b/tdt/cvs/cdk/root/release/rcS_neutrino
--- a/tdt/cvs/cdk/root/release/rcS_neutrino
+++ b/tdt/cvs/cdk/root/release/rcS_neutrino
@@ -122,14 +122,15 @@ if [ ! -e /var/etc/.firstboot ]; then
    echo "LOADING neutrino" > /dev/vfd
    echo "LOADING neutrino"
 
-   until false
-   do
-      echo "starting neutrino ->"
-      /usr/local/bin/neutrino
-      rtv=$?
-      echo "neutrino ended <- RTV: " $rtv
-      case "$rtv" in
-		0) echo "0"
+   if [ "$var" = 0 ]; then
+      until false
+      do
+         echo "starting neutrino ->"
+         /usr/local/bin/neutrino
+         rtv=$?
+         echo "neutrino ended <- RTV: " $rtv
+         case "$rtv" in
+	   	0) echo "0"
 		   echo "Box restart"
       		   reboot;;
 		1) echo "1"
@@ -144,8 +145,35 @@ if [ ! -e /var/etc/.firstboot ]; then
 		*) echo "*"
 		   echo "Unexpected error"
                    reboot;;
-      esac
-   done 
+         esac
+      done 
+   else
+# 14w shutdown fix? fp_control don't work on them?
+      until false
+      do
+         echo "starting neutrino ->"
+         /usr/local/bin/neutrino
+         rtv=$?
+         echo "neutrino ended <- RTV: " $rtv
+         case "$rtv" in
+	   	0) echo "0"
+	   	   echo "Box restart"
+      	   	   reboot;;
+	   	1) echo "1"
+	   	   echo "SHUTDOWN"
+		   case "$var" in
+			0) gotosleep
+                           umount -a;;
+  			1|3) gotosleep #please check if this works for ufs910 14W
+                             echo "0" > /proc/progress
+		             showiframe -p /boot/bootlogo.mvi &;;
+		   esac;;           
+		*) echo "*"
+		   echo "Unexpected error"
+                   reboot;;
+         esac
+      done 
+   fi
 fi
 
 #never reached
