merge tdt changes. thx to tdt for the updates

diff --git a/tdt/cvs/cdk/root/release/rcS_neutrino_fortis_hdbox b/tdt/cvs/cdk/root/release/rcS_neutrino_fortis_hdbox
--- a/tdt/cvs/cdk/root/release/rcS_neutrino_fortis_hdbox
+++ b/tdt/cvs/cdk/root/release/rcS_neutrino_fortis_hdbox
@@ -2,11 +2,12 @@
 
 MODDIR=/lib/modules
 
-insmod $MODDIR/micom.ko
+echo fortis hdbox
+
+insmod $MODDIR/nuvoton.ko
 
 if [ -e /var/etc/.firstboot ]; then
-   #fp_control does not work here
-   echo "WAIT 1 min" >/dev/vfd
+   echo "WAIT 1 min" > /dev/vfd
    echo "WAIT 1 min"
    rm /var/etc/.firstboot
    touch /dev/.devfsd
@@ -15,7 +16,6 @@ fi
 /etc/init.d/mountvirtfs start
 
 insmod $MODDIR/e2_proc.ko
-insmod $MODDIR/fan_ctrl.ko
 
 if [ ! -e /var/etc/.firstboot ]; then
 
@@ -28,11 +28,10 @@ if [ ! -e /var/etc/.firstboot ]; then
 
    echo "init stmfb"
    insmod $MODDIR/stmcore-display-stx7109c3.ko
-   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:12m:pal:yuv:yuv;# display1=720x576-16@50:1m:pal:cvbs;
+   insmod $MODDIR/stmfb.ko display0=1280x720-32@60:12m:pal:yuv:yuv;# display1=720x576-16@50:1m:pal:cvbs;
 
    echo "LOADING MODULES"   
-   fp_control -c
-   fp_control -t "LOADING MODULES"
+   echo "LOADING MODULES" >/dev/vfd
 
    echo "load a/v firmware"
    /bin/stslave -t stb7100.0 -R /boot/video.elf
@@ -41,7 +40,7 @@ if [ ! -e /var/etc/.firstboot ]; then
    echo "init embx"
    insmod $MODDIR/embxshell.ko
    insmod $MODDIR/embxmailbox.ko mailbox0=0xb9211000:136:set2 mailbox1=0xb9212000:0 ;
-   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:512:0xa4000000:0x10000000 ;
+   insmod $MODDIR/embxshm.ko mailbox0=shm:0:7:0x60000000:0:256:256:0:1024:0xa4000000:0x10000000 ;
    insmod $MODDIR/mme_host.ko transport0=shm
 
    echo "init AVS"
@@ -49,13 +48,13 @@ if [ ! -e /var/etc/.firstboot ]; then
 
    echo "init player"
    insmod $MODDIR/mmelog.ko
-   insmod $MODDIR/mpeg2hw.ko mmeName=HW_MPEG2_TRANSFORMER;
+   insmod $MODDIR/mpeg2hw.ko mmeName=MPEG2_TRANSFORMER1;
    insmod $MODDIR/ksound.ko
    insmod $MODDIR/stm_v4l2.ko
    insmod $MODDIR/pseudocard.ko
 
-   insmod $MODDIR/cx21143.ko
-   insmod $MODDIR/ufs922_cic.ko
+   insmod $MODDIR/stv090x.ko
+   insmod $MODDIR/cimax.ko
    insmod $MODDIR/pti.ko
    insmod $MODDIR/stmdvb.ko
    insmod $MODDIR/stm_monitor.ko
@@ -63,65 +62,60 @@ if [ ! -e /var/etc/.firstboot ]; then
    insmod $MODDIR/sth264pp.ko
    insmod $MODDIR/stmalloc.ko
    insmod $MODDIR/platform.ko
-   insmod $MODDIR/silencegen.ko
 
-   #showiframe -p /boot/bootlogo.mvi &
-   #stfbcontrol a 0
+ #  showiframe -p /boot/bootlogo.mvi &
+   stfbcontrol a 0
 
    echo "init frontpanel"
    insmod $MODDIR/boxtype.ko
    insmod $MODDIR/simu_button.ko
+   insmod $MODDIR/nuvoton.ko
 
    mknod /dev/rc c 147 1 
-
-   #toggleFeedback 0 = false, 1 = true
-   #maxRate (same key) = 2, maxDelay (determine new key) = 500
-   /bin/evremote2 0 2 500 &
+   #maxRate (same key) = 3, maxDelay (determine new key) = 150
+   /bin/evremote2 3 300 &
 
    #DVD-PLAYER EXIT-TASTE LOAD OR EJECT DVD
    #mount /dev/sr0 /media/dvd
    #fix this later if we got to manage a marusys raw device driver
-   mount /dev/sda5 /hdd/
+#   mount /dev/sda5 /hdd/
 
    /etc/init.d/portmap start
    /etc/init.d/vsftpd start
    /usr/sbin/inetd
-
    #timefix e2
    date -s "121220001970"
 
-   #stfbcontrol a 255
+   stfbcontrol a 255
 
-   fp_control -t "LOADING neutrino"
-   echo "LOADING neutrino"
+   echo "Load Neutrino" > /dev/vfd
+   echo "Load Neutrino"
 
-   until false
-   do
-      echo "starting neutrino ->"
-      /usr/local/bin/neutrino -f -u
-      rtv=$?
-      echo "neutrino ended <- RTV: " $rtv
-      case "$rtv" in
-		0) echo "0"
-		   echo "SHUTDOWN"
-		   sync
-		   umount -a -l -f;;
-		1) echo "1"
-		   echo "SHUTDOWN"
-		   sync
-		   fp_control -e
-		   umount -a -l -f;;
-		2) echo "2"
-		   echo "BOX RESTART"
-		   reboot -f;;
-		*) echo "*"
-		   echo "Unexpected error"
-                   reboot;;
-      esac
-   done 
+until false
+do
+ echo "starting neutrino ->"
+ /usr/local/bin/neutrino
+ rtv=$?
+ echo "neutrino ended <- RTV: " $rtv
+ case "$rtv" in
+     0) echo "0"
+        echo "Box restart"
+	reboot;;
+     1) echo "1"
+	echo "SHUTDOWN"
+        case "$var" in
+          0) fp_control -e
+    	     umount -a;;
+    	1|3) fp_control -e please check if this works for ufs910 14W
+             echo "0" > /proc/progress
+        esac;;           
+     *) echo "*"
+        echo "Unexpected error"
+        reboot;;
+ esac
+ done
 fi
-
 #never reached
-echo "REBOOT UFS922" > /dev/vfd
-echo "REBOOT UFS922"
+echo "REBOOT HDBOX" > /dev/vfd
+echo "REBOOT HDBOX"
 reboot
