[spark] add TSsource to rcS

diff --git a/tdt/cvs/cdk/root/etc/init.d/rcS_spark b/tdt/cvs/cdk/root/etc/init.d/rcS_spark
--- a/tdt/cvs/cdk/root/etc/init.d/rcS_spark
+++ b/tdt/cvs/cdk/root/etc/init.d/rcS_spark
@@ -1,9 +1,11 @@
 #!/bin/sh
 
 MODDIR=/lib/modules
-
+echo "init frontpanel"
 insmod $MODDIR/vfd.ko
 insmod $MODDIR/aotom.ko
+insmod $MODDIR/simu_button.ko
+insmod $MODDIR/encrypt.ko
 
 if [ -e /var/etc/.firstboot ]; then
    echo "WAIT 1 min" >/dev/vfd
@@ -12,18 +14,14 @@ if [ -e /var/etc/.firstboot ]; then
    touch /dev/.devfsd
 fi
 
-echo "mount" > /dev/vfd
-
 /etc/init.d/mountvirtfs start
-
 /etc/init.d/portmap start
 
-#echo "starting telnetd"
-#/usr/sbin/telnetd -l /bin/login
 insmod $MODDIR/e2_proc.ko
 
 # start automounter with umount timeout of 5 seconds
-#/usr/sbin/automount --timeout=5 /autofs file /etc/auto.usb
+insmod $MODDIR/autofs4.ko
+/usr/sbin/automount --timeout=5 /autofs file /etc/auto.usb
 
 if [ ! -e /var/etc/.firstboot ]; then
 
@@ -34,30 +32,21 @@ if [ ! -e /var/etc/.firstboot ]; then
    echo "starting telnetd"
    /usr/sbin/telnetd -l /bin/login
 
-   insmod $MODDIR/simu_button.ko
-
-   echo "init lircd"
-   /usr/bin/lircd
-
-   /bin/evremote2 spark &
- 
    echo "init stmfb"
    insmod $MODDIR/stmcore-display-sti7111.ko
-   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:10m:pal:yuv:yuv #display1=720x576-16@50:3m:pal:cvbs;
+   insmod $MODDIR/stmfb.ko display0=1280x720-32@50:15m:pal:yuv:yuv
 
    echo "LOADING MODULES"   
-   echo "LOADING MODULES" > /dev/vfd
+   echo "LOAD" > /dev/vfd
 
-   if [ -e /boot/audio.elf ]; then
-	  echo "load a firmware"
-   else
-       echo "FW MISSING!!!"
+   if [ ! -e /boot/audio.elf ]; then
+      echo "FW MISSING!!!"
    fi
 
    echo "load a firmware"
-   /bin/ustslave_stm23 /dev/st231-1 /boot/audio.elf
+   /bin/ustslave /dev/st231-1 /boot/audio.elf
    echo "load v firmware"
-   /bin/ustslave_stm23 /dev/st231-0 /boot/video.elf
+   /bin/ustslave /dev/st231-0 /boot/video.elf
 
    echo "init embx"
    insmod $MODDIR/embxshell.ko
@@ -66,35 +55,38 @@ if [ ! -e /var/etc/.firstboot ]; then
    insmod $MODDIR/mme_host.ko transport0=shm
 
    echo "init AVS"
-   insmod $MODDIR/avs.ko type=spark_avs #type=stv6417
+   insmod $MODDIR/avs.ko type=avs_pio
 
    player=`cat /proc/stb/player/version`
-   if [ $player=='player179' ]; then
-	echo "[rcS] init player 179"
-   else
-	echo "[rcS] init player 131"
-   fi
+   player=`cat /proc/stb/player/version | awk '{ print substr( $0, length($0) - 2, length($0) ) }'`
+   echo "init player $player"
+
    insmod $MODDIR/mmelog.ko
    insmod $MODDIR/ksound.ko
    insmod $MODDIR/p2div64.ko
    insmod $MODDIR/stm_v4l2.ko
-   if [ $player=='player179' ]; then
-	insmod $MODDIR/stmvout.ko
-	insmod $MODDIR/stmvbi.ko
+   if [ $player -gt 131 ]; then
+      insmod $MODDIR/stmvout.ko
+      insmod $MODDIR/stmvbi.ko
    fi
    insmod $MODDIR/pseudocard.ko
 
    insmod $MODDIR/stv090x.ko
-   if [ $player=='player179' ]; then
-	insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
-	insmod $MODDIR/stm_monitor.ko
-	insmod $MODDIR/stmsysfs.ko
-    insmod $MODDIR/stmdvb.ko highSR=1 swts=1
+   if [ $player -gt 131 ]; then
+      # Full feature pti
+      insmod $MODDIR/pti.ko waitMS=20 videoMem=4096
+      if [ $?=='2' ]; then
+         # Simple pti
+         insmod $MODDIR/pti.ko
+      fi
+      insmod $MODDIR/stm_monitor.ko
+      insmod $MODDIR/stmsysfs.ko
+      insmod $MODDIR/stmdvb.ko TSsource0=0;
    else
-	insmod $MODDIR/pti.ko
-    insmod $MODDIR/stmdvb.ko
-	insmod $MODDIR/stm_monitor.ko
-   fi	
+      insmod $MODDIR/pti.ko
+      insmod $MODDIR/stmdvb.ko
+      insmod $MODDIR/stm_monitor.ko
+   fi
    insmod $MODDIR/player2.ko
    insmod $MODDIR/sth264pp.ko
    insmod $MODDIR/stmalloc.ko
@@ -102,34 +94,52 @@ if [ ! -e /var/etc/.firstboot ]; then
    insmod $MODDIR/silencegen.ko
    insmod $MODDIR/smartcard.ko
 
+   insmod $MODDIR/bpamem.ko
+   mknod /dev/bpamem c 153 0 
+
    showiframe -p /boot/bootlogo.mvi &
    stfbcontrol a 0
 
-   echo "init frontpanel"
+   echo "init lircd"
+   /usr/bin/lircd
 
    mknod /dev/rc c 147 1 
    mknod /dev/sci0 c 169 0
    mknod /dev/sci1 c 169 1 
+   major=$(awk "\$2==\"sparkid\" {print \$1}" /proc/devices)
+   rm -f /dev/sparkid
+   mknod /dev/sparkid c $major 0 
 
-   #toggleFeedback 0 = false, 1 = true
-   #maxRate (same key) = 2, maxDelay (determine new key) = 500
-   #/bin/evremote2 1 2 500 &
-
-   # timefix e2
-   # date -s "121220001970"
+   /bin/evremote2 spark &
 
    stfbcontrol a 255
 
-   echo "LOADING E2"
-
    /etc/init.d/mountall start
-
    /etc/init.d/hostname start
 
    echo "starting telnetd"
    /usr/sbin/telnetd -l /bin/login
    /etc/init.d/vsftpd start
    /usr/sbin/inetd
+
+   NFS=`grep -c nfs /proc/cmdline`
+   if [ "$NFS" -eq "1" ]; then 
+      echo "Booting from nfs, don't set network" 
+   else 
+      if [ -e /etc/network/interfaces ]; then 
+	 ip addr flush eth0 
+	 /etc/init.d/networking stop 
+	 DHCP=`grep -c dhcp /etc/network/interfaces`
+	 if [ "$DHCP" -eq "1" ]; then 
+	    echo "Starting dhcp"
+            /etc/init.d/udhcpc start 
+	 fi 
+	 /etc/init.d/networking start 
+      fi 
+   fi
+
+   echo "run" > /dev/vfd
+   echo "LOADING E2"
 
    until false
    do
@@ -140,21 +150,20 @@ if [ ! -e /var/etc/.firstboot ]; then
       case "$rtv" in
 		0) echo "0"
 		   echo "E2 ERROR"
-      		   reboot;;
+		   init 6;;
 		1) echo "1"
 		   echo "SHUTDOWN"
-                   sync
-                   umount -a;;
+		   init 0;;
 		2) echo "2"
 		   echo "REBOOT"
-		   reboot;;
+		   init 6;;
 		3) echo "3"
 		   echo "E2 RESTART"
 		   echo "0" > /proc/progress
 		   showiframe -p /boot/bootlogo.mvi &;;
 		*) echo "*"
 		   echo "ERROR"
-                   reboot;;
+		   init 6;;
       esac
    done 
 fi
@@ -162,4 +171,5 @@ fi
 #never reached
 echo "REBOOT SPARK" > /dev/vfd
 echo "REBOOT SPARK"
-reboot
+reboot -f
+
